title: Program City
description: "Software Engineer Blogger"
author:
  name: "Veck Hsiao"
  email: "fbukevi@gmail.com"
  url: "https://veck.im/engineer"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: "Veck"
year: "2020"

theme: jekyll-theme-cayman